### PR TITLE
Fix timer callback count is wrong when low fps

### PR DESCRIPTION
**Pull request by xmxiaoq**
Fix for #53 
Timer callback count is less than it should be when low fps. Elapsed time is not fully consumed.
Code rely on callback count has trouble.

### CODE REVIEW

**Comment by fairygui** [comment]
The code is not correct, please check.
"Use a loop to consume all the elapsed time", so no matter what the value of ‘interval' is, the timer will trigger every frame?

**Comment by xmxiaoq** [comment]
Sorry i misunderstand it. The timer is triggered at most once every frame, this is **on purpose**, because fairygui internal depend on this behaviour.  I didn't realize that ^^
Please close #53

**Comment by xmxiaoq** [comment]
I want to add some comment in FairyGUI.lua to clarify this, is that welcome?

**Comment by fairygui** [comment]
Yes, of course.

**Pull request closed without merging**
